#!/usr/bin/bash
# 
# Runs getnPlot.py under proper conda environment for rockfalls
# (assumes time is first pick time)

eval "$(conda shell.bash hook)"

if [ "$HOSTNAME" = "opsproc2" ]; then
    conda activate >/dev/null 2>&1
else
    conda activate obspy >/dev/null 2>&1
fi

freqHP=0.5

mkdir -p tmpGetNPlot
cd tmpGetNPlot
rm -f *.*

getnPlot -q --pre 5 --dur 30 --shape square --hpfilt $freqHP "$@" 
getnPlot -q --pre 2 --dur 10 --shape square --kind 3C --sta MBFR,MBLY,MBLG --hpfilt $freqHP "$@"
getnPlot -q --pre 5 --dur 30 --kind tfr --sta MSS1 --fmin 1.0 --fmax 50.0 --hpfilt $freqHP "$@"
getnPlot -q --pre 5 --dur 30 --kind tfr --sta MBFR --fmin 1.0 --fmax 50.0 --hpfilt $freqHP "$@"
getnPlot -q --pre 5 --dur 30 --kind tfr --sta MBLG --fmin 1.0 --fmax 50.0 --hpfilt $freqHP "$@"
getnPlot -q --pre 5 --dur 30 --kind tfr --sta MBLY --fmin 1.0 --fmax 50.0 --hpfilt $freqHP "$@"
getnPlot -q --pre 60 --dur 180 --kind Z --sta MSS1,MBFL,MBRV --shape xxlong --plotfile basement "$@"

conda deactivate >/dev/null 2>&1

magick mogrify -crop 1815x317+74+59 basement.png
magick mogrify -resize 4486x600! basement.png

magick mogrify -crop 1654x1113+86+117 *tfr*.png
magick mogrify -resize 638x480! *tfr*.png

magick montage *MSS1-Z-tfr*.png *MBFR-Z-tfr*.png *MBLY-Z-tfr*.png *MBLG-Z-tfr*.png -tile 1x4 -geometry +1+1 tmp.png

files=(*)
fname=$files
fname2=${fname//allz/special}
magick montage *allz*.png tmp.png *3C*.png -tile 3x1 -geometry +1+1 aboveground.png
magick montage aboveground.png basement.png -tile 1x2 -geometry +1+1 "${fname2}"

mv ${fname2} ..

cd ..
rm -r tmpGetNPlot
