#!/usr/bin/bash
# 
# Runs getnPlot.py under proper conda environment for interesting event
# (assumes time is first pick time)

all_args=("$@")
first_arg="$1"
rest_args=("${all_args[@]:1}")

eval "$(conda shell.bash hook)"

if [ "$HOSTNAME" = "opsproc2" ]; then
    conda activate >/dev/null 2>&1
else
    conda activate obspy >/dev/null 2>&1
fi

mkdir -p tmpGetNPlot
cd tmpGetNPlot
rm -f *.*

getnPlot -q --pre 5 --dur 30 --shape portrait "${rest_args[@]}"
getnPlot -q --pre 5 --dur 30 --shape portrait --kind 3C "${rest_args[@]}" --sta "$first_arg"
getnPlot -q --pre 5 --dur 30 --shape square --kind tfr "${rest_args[@]}" --sta "$first_arg"

conda deactivate >/dev/null 2>&1

files=(*)
fname=$files
fname2=${fname//allz/special4}

magick montage *.png -geometry +0+0 "${fname2}"

mv ${fname2} ..
cd ..
rm -r tmpGetNPlot
