#!/usr/bin/bash
# 
# Runs getnPlot.py under proper conda environment for interesting event
# (assumes time is first pick time)

eval "$(conda shell.bash hook)"

if [ "$HOSTNAME" = "opsproc2" ]; then
    conda activate >/dev/null 2>&1
else
    conda activate obspy >/dev/null 2>&1
fi

mkdir -p tmpGetNPlot
cd tmpGetNPlot
rm -f *.*

getnPlot -q --pre 30 --dur 150 --shape xlong "$@"
getnPlot -q --pre 30 --dur 150 --shape xlong --kind close3C "$@"

conda deactivate >/dev/null 2>&1

files=(*)
fname=$files
fname2=${fname//allz/special5}

magick montage *.png -tile 1x2 -geometry +0+0 "${fname2}"

mv ${fname2} ..
cd ..
rm -r tmpGetNPlot
