#!/usr/bin/bash

./getnPlot.py --date 2022-12-26 --time 15:31:07.7 --tag test000
./getnPlot.py --date 2022-12-26 --time 15:31:07.7 --kind allZ --tag test001_allZ
./getnPlot.py --date 2022-12-26 --time 15:31:07.7 --kind all3C --tag test002_all3C

./getnPlot.py --date 2022-12-26 --time 15:31:07.7 --kind closeZ --tag test003_closeZ
./getnPlot.py --date 2022-12-26 --time 15:31:07.7 --kind close3C --tag test004_close3C

./getnPlot.py --date 2022-12-26 --time 15:31:07.7 --kind radianZ --tag test005_radianZ
./getnPlot.py --date 2022-12-26 --time 15:31:07.7 --kind radian3C --tag test006_radian3C

./getnPlot.py --date 2022-12-26 --time 15:31:07.7 --kind irishZ --tag test007_irishZ
./getnPlot.py --date 2022-12-26 --time 15:31:07.7 --kind irish3C --tag test008_irish_3C

./getnPlot.py --date 2023-01-19 --time 11:17:43 --kind tfr --tag test009_tfr
./getnPlot.py --date 2023-01-19 --time 11:17:43 --kind tfr --sta MBLY --tag test010a_tfr_mbly
./getnPlot.py --date 2023-01-19 --time 11:17:43 --kind tfr --sta MBLY --fmin 0.1 --fmax 10.0 --tag test010b_tfr_mbly_fed

./getnPlot.py --date 2023-01-19 --time 11:17:43 --kind Z --tag test011a_Z
./getnPlot.py --date 2023-01-19 --time 11:17:43 --kind Z --plotspec --tag test011b_Z_plotspec
./getnPlot.py --date 2023-01-19 --time 11:17:43 --kind Z --fscale log --plotspec --tag test011c_Z_log_plotspec
./getnPlot.py --date 2023-01-19 --time 11:17:43 --kind Z --zscale amp --fscale log --plotspec --tag test011d_Z_log_plotspec
./getnPlot.py --date 2023-01-19 --time 11:17:43 --kind Z --zscale power --fscale log --plotspec --tag test011e_Z_log_plotspec
./getnPlot.py --date 2023-01-19 --time 11:17:43 --kind Z --zscale log --fscale log --plotspec --tag test011f_Z_log_plotspec
./getnPlot.py --date 2023-01-19 --time 11:17:43 --kind Z --zscale sqrt --fscale log --plotspec --tag test011g_Z_log_plotspec
./getnPlot.py --date 2023-01-19 --time 11:17:43 --kind 3C --tag test012a_3C
./getnPlot.py --date 2023-01-19 --time 11:17:43 --kind 3C --fscale log --tag test012b_3C_log

./getnPlot.py --date 2023-01-19 --time 11:17:43 --kind Z --sta MSS1,MBLY,MBLG --tag test013_Z_mss1_mbly_mblg
./getnPlot.py --date 2023-01-19 --time 11:17:43 --kind 3C --sta MBLY,MBLG --tag test014_3C_mbly_mblg

./getnPlot.py --date 2023-01-19 --time 11:17:43 --kind rockfall --tag test015_rockfall

./getnPlot.py --date 2022-12-15 --time 00:04 --kind lahar --pre 10m --dur 60m --tag test016a_lahar
./getnPlot.py --date 2022-12-15 --time 00:04 --kind lahar --pre 10m --dur 60m --plotnorms --tag test016b_lahar_norms
./getnPlot.py --date 2022-12-15 --time 00:04 --kind lahar --pre 10m --dur 60m --plotnorms --fmin 5.0 --fmax 10.0 --tag test016c_lahar_norms_fed
./getnPlot.py --date 2022-12-15 --time 00:04 --kind lahar --pre 10m --dur 60m --zscale power --tag test016d_lahar_power
./getnPlot.py --date 2022-12-15 --time 00:04 --kind lahar --pre 10m --dur 60m --fscale linear --tag test016e_lahar_linear
./getnPlot.py --date 2022-12-15 --time 00:04 --kind lahar --pre 10m --dur 60m --fscale log --tag test016f_lahar_log
./getnPlot.py --date 2022-12-15 --time 00:04 --kind lahar --pre 10m --dur 60m --fscale log --fmin 1.0 --fmax 20.0 --tag test016g_lahar_log_fed
./getnPlot.py --date 2022-12-15 --time 00:04 --kind lahar --pre 10m --dur 60m --zscale sqrt --fscale log --fmin 1.0 --fmax 100.0 --tag test016h_sqrt_lahar_log_fed
